# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

original_repo: https://github.com/pyladiesrecife/pyladiesrecife.github.io
title: PyLadies Recife
email: recife@pyladies.com
attendees_form: 
description: O PyLadies Recife é um capítulo do PyLadies Global desde 2016 e é uma das comunidades de tecnologia mais ativas da região. Contamos com mais de 200 pessoas integrantes buscando alcançar o objetivo de levar inclusão de mulheres e pessoas não binárias na tecnologia.
keywords: mulheres, tecnologia, Recife, evento, PyLadies Recife, PyLadies, Python
ogimage: "/assets/images/logo.svg"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://pyladiesrecife.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: pyladies_recife
github_username: pyladiesrecife

sass:
    sass_dir: assets/_scss
    style: compressed

# Build settings
# theme: minima
# plugins:
#   - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
